# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  user:
    text: 关于
    url: /about
  github:
    url: https://github.com/zshellzhang1993-2025
    target: _blank

# 你的头像url
avatar: https://avatars0.githubusercontent.com/u/8027247?s=460&v=4
# avatar link
avatar_link: https://avatars0.githubusercontent.com/u/8027247?s=460&v=4
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: xaaservice@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签页
archives_title: 文章归档
categories_title: 文章分类

# 文章截断
excerpt_render: true
excerpt_length: 200
excerpt_link:
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: false

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢支持!
  wechat: /img/wechat.jpg     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
#toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: <strong>本文链接:</strong> <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" rel="external"><%- page.permalink.replace(/index\.html$/, '').replace(/\/$/, '') %></a> <br/> 感谢您的阅读与支持！

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
#gitment:
#   owner: zhangzhi1993-2025
#   repo: gitment-storage
#   client_id: 8d7b7d33dd8bbd51a8c2
#   client_secret: a98d9b9266c6ccbae7b1194e1680dba27def86ee

# Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId: fMh2JHgkPnDtARiQapOg8Jrk-gzGzoHsz
  appKey: UPNXLDUkngDnuhfC9XQPgF6n
  notify: true # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 您的评论, 吾愿洗耳恭听! # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size



# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: http://zshell.cc

# 版权起始年份
since_year: 2016

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 日积跬步，以至千里。沉心静气，修炼内功。

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
#visit_counter:
#  site_uv: 站点总访客数：
#  site_pv: 站点总访问量：

# 动态定义title
#title_change:
#  normal: (つェ⊂)咦, 又回来啦!
#  leave: 怎么走了?

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false

# 开启数学公式渲染
mathjax: true

